In [86]:
import numpy as np
import pandas as pd

REading Dataset


In [87]:
dataset = pd.read_csv("/content/auto-mpg.csv")


In [88]:
dataset.head()

mpg  cylinders  displacement  ...  model year  origin                   car name
0  18.0          8         307.0  ...          70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...          70       1          buick skylark 320
2  18.0          8         318.0  ...          70       1         plymouth satellite
3  16.0          8         304.0  ...          70       1              amc rebel sst
4  17.0          8         302.0  ...          70       1                ford torino

[5 rows x 9 columns]

Data preprocessing


In [4]:
dataset.isnull().any()

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model year      False
origin          False
car name        False
dtype: bool

In [5]:
x = dataset.iloc[:,1:8].values
y = dataset.iloc[:,0].values

In [6]:
x

array([[  8. , 307. , 130. , ...,  12. ,  70. ,   1. ],
       [  8. , 350. , 165. , ...,  11.5,  70. ,   1. ],
       [  8. , 318. , 150. , ...,  11. ,  70. ,   1. ],
       ...,
       [  4. , 135. ,  84. , ...,  11.6,  82. ,   1. ],
       [  4. , 120. ,  79. , ...,  18.6,  82. ,   1. ],
       [  4. , 119. ,  82. , ...,  19.4,  82. ,   1. ]])

In [7]:
y

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [69]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.1,random_state= 0)

In [70]:
x_train

array([[  8. , 454. , 220. , ...,   9. ,  70. ,   1. ],
       [  8. , 350. , 165. , ...,  11.5,  70. ,   1. ],
       [  4. , 121. ,  80. , ...,  15. ,  79. ,   1. ],
       ...,
       [  4. ,  68. ,  49. , ...,  19.5,  73. ,   2. ],
       [  6. , 250. , 100. , ...,  15. ,  71. ,   1. ],
       [  4. ,  90. ,  71. , ...,  16.5,  75. ,   2. ]])

Random Forest Algoritham 

In [71]:
from sklearn.ensemble import RandomForestRegressor
d = RandomForestRegressor(n_estimators=10,random_state=0)
d.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [72]:
ypred = d.predict(x_test)

In [73]:
ypred

array([14.55, 24.7 , 14.35, 20.5 , 18.2 , 30.9 , 33.96, 20.61, 15.5 ,
       26.33, 35.02, 39.36, 19.15, 25.7 , 16.3 , 34.55, 27.34, 27.34,
       16.52, 35.61, 15.8 , 23.5 , 23.07, 21.  , 30.96, 25.7 , 33.52,
       30.89, 33.27, 16.07, 19.1 , 32.09, 17.34, 33.46, 21.11, 24.25,
       19.02, 15.35, 35.21, 12.  ])

In [74]:
y_test

array([14. , 25. , 13. , 21. , 18. , 35. , 34.1, 20. , 15. , 23.5, 40.9,
       37.2, 18. , 23. , 15.5, 35.7, 31. , 27. , 18. , 37.3, 15.5, 23. ,
       24. , 18. , 34.5, 25.4, 36.1, 34. , 30. , 16. , 18.6, 37. , 15. ,
       33.5, 22.4, 24. , 19. , 16.9, 31.9, 12. ])

Finding Accuracy

In [75]:
from sklearn.metrics import r2_score
accuracy = r2_score(ypred,y_test)

In [89]:
accuracy

0.9146674382281946

In [90]:
yp = d.predict([[8,307,130,3504,12,70,1]])

In [91]:
yp

array([17.5])

In [92]:
dataset.head()

mpg  cylinders  displacement  ...  model year  origin                   car name
0  18.0          8         307.0  ...          70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...          70       1          buick skylark 320
2  18.0          8         318.0  ...          70       1         plymouth satellite
3  16.0          8         304.0  ...          70       1              amc rebel sst
4  17.0          8         302.0  ...          70       1                ford torino

[5 rows x 9 columns]

In [93]:
yp = d.predict([[8,250,115,3003,25,80,2]])

In [82]:
yp

array([25.71])

In [83]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([],remainder = "passthrough")
x = ct.fit_transform(x)

Pickel File Creation

In [94]:
import pickle 
pickle.dump(d,open('carperformance.pkl','wb'))